#!/bin/bash

mkdir -p $REPOSITORY_ROOT
while read repo; do
	if [[ ! -e "$REPOSITORY_ROOT/$(basename $repo)" ]]; then
		echo "mirroring $repo"
		git clone --mirror $repo $REPOSITORY_ROOT/$(basename $repo)
	fi
done < ${WORKSPACE}/project/external-projects

